### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by rkarwacki** [rkarwacki/myframe#1]
User has to register via email and confirm the registration process by clicking a link in received email.
Can the token we send expire after a certain amount of time if user doesn't click in the link? Can the user request another token? 

Fields required during registration process:

- e-mail
- username (?)
- password and its confirmation
- name
- occupation
- how long has he been in Poland
- which languages does he speak (do we provide a list of languages?)

Any more? 
Does user log in to the platform using the e-mail or picks a username?

**Comment by weronikawu** [comment]
If the token will expire, the user can request another one with the same email.
How is it easier for you - to use the e-mail. pick the username or can both options run simultaneusly?

**Comment by rkarwacki** [comment]
It's not that much of a difference. But I think it could be difficult to remember your username if you don't visit the site often, so I suggest logging in using your e-mail and picking a "display username" which will be visible, because we don't want to expose somebody's e-mail address in the public pages, really.
