### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by rkarwacki** [rkarwacki/myframe#6]
Which languages do we support?

**Comment by weronikawu** [comment]
English is the primary language.
Other languagues will be supported depending on the volunteers language skills. 
Each user has to mark the languages she's speaking.

**Comment by rkarwacki** [comment]
Ok, and what about the platform in general? I think it's reasonable to implement internationalization of the webpages, for example the user can switch to German and see the portal translated, e.g "Login" would be "Anmelden" and so on. 

I think English, German and Polish are reasonable to implement. Italian, too, maybe?

**Comment by weronikawu** [comment]
Of course I feel into! 
I'd even rank Spanish above Italian. Russian/Ukrainian will also be crucial. 
I'll work on it.

**Comment by rkarwacki** [comment]
Good. I will try to implement it in such a way that adding another language will be relatively easy.
